In [1072]:
import numpy as np
import pandas as pd

In [1073]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [1074]:
df = pd.read_csv('gurgaon_properties.csv')

In [1075]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,area,property_id
3027,4 BHK Flat in Palam Vihar,flat,palam vihar society,3.350,7444.0,4500.0,Carpet area: 4500 (418.06 sq.m.),4,4,3+,study room,"1057, Palam Vihar, Gurgaon, Haryana",2.0,Not Available,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Visit the property one and you will find the u...,"['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Lift(s)', 'High Ceiling Height', 'Maintenanc...","['Environment5 out of 5', 'Safety4 out of 5', ...",NaN,NaN
496,5 Bedroom House for sale in Palam Vihar,house,independent,6.000,24691.0,2430.0,Plot area 270(225.75 sq.m.),5,6,3+,"pooja room,study room,others","Palam Vihar, Gurgaon, Haryana",3.0,East,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Very nicely built up independent duplex house ...,"['7 Wardrobe', '12 Fan', '1 Exhaust Fan', '7 G...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",(226 sq.m.) Plot Area,B67592164
2904,2 BHK Flat in Sector 95 Gurgaon,flat,rof ananda,0.315,5736.0,549.0,Carpet area: 549.16 (51.02 sq.m.),2,2,1,pooja room,"1002, Sector 95 Gurgaon, Gurgaon, Haryana",10.0,North,1 to 5 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...",This 2 bhk apartment is available for sale in ...,"['1 Water Purifier', '5 Fan', '1 Dining Table'...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Lifestyle4.5 out of...",NaN,NaN
1563,4 Bedroom House for sale in South City 1,house,independent,11.000,33951.0,3240.0,Plot area 360(301.01 sq.m.),4,4,2,"pooja room,study room,servant room","South City 1, Gurgaon, Haryana",3.0,East,0 to 1 Year Old,"['Huda city centre metro station', 'Axis bank ...",Very well connected property from nh8 and conn...,"['5 Wardrobe', '9 Fan', '4 Geyser', '12 Light'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",(301 sq.m.) Plot Area,J69424116
3514,4 Bedroom House for sale in Sector 112 Gurgaon,house,experion windchants,7.990,12519.0,6382.0,Built Up area: 6382 (592.91 sq.m.),4,6,3,"servant room,store room,pooja room","Wp1- Wp-8, Sector 112 Gurgaon, Gurgaon, Haryana",2.0,South-East,0 to 1 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale 4bhk + servant luxury villa...,"['1 Exhaust Fan', '7 Geyser', '1 Stove', '10 A...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",(593 sq.m.) Built-up Area,H57070296

In [1076]:
df.shape

(3959, 22)

In [1077]:
df.duplicated().sum()

np.int64(0)

In [1078]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3959 entries, 0 to 3958
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3959 non-null   object
 1   property_type    3959 non-null   object
 2   society          3959 non-null   object
 3   price            3939 non-null   float64
 4   price_per_sqft   3939 non-null   float64
 5   Estimated_area   3939 non-null   float64
 6   areaWithType     3959 non-null   object
 7   bedRoom          3959 non-null   int64
 8   bathroom         3959 non-null   int64
 9   balcony          3959 non-null   object
 10  additionalRoom   3959 non-null   object
 11  address          3948 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           3959 non-null   object
 14  agePossession    3958 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3959 non-null   object
 17  furnishDetails   2927 non-null   object
 18  features         3252 non-null   object
 19  rating           3510 non-null   object
 20  area             964 non-null    object
 21  property_id      964 non-null    object
dtypes: float64(4), int64(2), object(16)
memory usage: 680.6+ KB

In [1079]:
df = df.drop(columns=['area'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3959 entries, 0 to 3958
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3959 non-null   object
 1   property_type    3959 non-null   object
 2   society          3959 non-null   object
 3   price            3939 non-null   float64
 4   price_per_sqft   3939 non-null   float64
 5   Estimated_area   3939 non-null   float64
 6   areaWithType     3959 non-null   object
 7   bedRoom          3959 non-null   int64
 8   bathroom         3959 non-null   int64
 9   balcony          3959 non-null   object
 10  additionalRoom   3959 non-null   object
 11  address          3948 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           3959 non-null   object
 14  agePossession    3958 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3959 non-null   object
 17  furnishDetails   2927 non-null   object
 18  features         3252 non-null   object
 19  rating           3510 non-null   object
 20  property_id      964 non-null    object
dtypes: float64(4), int64(2), object(15)
memory usage: 649.7+ KB

In [1080]:
df.isnull().sum()

property_name         0
property_type         0
society               0
price                20
price_per_sqft       20
Estimated_area       20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             19
facing                0
agePossession         1
nearbyLocations     205
description           0
furnishDetails     1032
features            707
rating              449
property_id        2995
dtype: int64

In [1081]:
df.head()

,property_name,property_type,society,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss,1.18,7170.0,1646.0,Super Built up area 1640(152.36 sq.m.)Built Up...,2,2,3,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Ekta Hospital', ...",This lovely 2 bhk apartment/flat in sector 85 ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5...",NaN
1,5 Bedroom House for sale in Sushant Lok Phase 3,house,independent,8.31,24171.0,3438.0,Plot area 382(319.4 sq.m.),5,6,3+,"store room,pooja room,servant room,study room","Corner Villa, Sushant Lok Phase 3, Gurgaon, Ha...",4.0,North-East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...","Sushant lok-3\nBlock-B, corner villa at plot r...",[],"['Feng Shui / Vaastu Compliant', 'False Ceilin...","['Environment4 out of 5', 'Lifestyle4 out of 5...",E69994668
2,5 Bedroom House for sale in Dayanand Colony,house,independent,1.25,11574.0,1080.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,5,5,1,pooja room,"34/4, 8 Biswa, Daya Kishan Katariya Marg, Daya...",2.0,South,0 to 1 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Interested to sell independent house/villa.It ...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5...",S68260580
3,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,0.95,6209.0,1530.0,Super Built up area 1530(142.14 sq.m.),2,2,3,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",7.0,North-East,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Right next to the new golf course road, m3m an...","['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5...",NaN
4,3 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,3.20,11500.0,2783.0,Super Built up area 2781(258.36 sq.m.),3,4,3+,not available,"204, Sector 22 Gurgaon, Gurgaon, Haryana",2.0,North-East,Within 6 months,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Right in heart of gurgaon and delhi is just 2k...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E...",NaN

In [1082]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [1083]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss,Sector 85,1.18,7170.0,1646.0,Super Built up area 1640(152.36 sq.m.)Built Up...,2,2,3,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Ekta Hospital', ...",This lovely 2 bhk apartment/flat in sector 85 ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5...",NaN
1,5 Bedroom House for sale in Sushant Lok Phase 3,house,independent,Sushant Lok Phase 3,8.31,24171.0,3438.0,Plot area 382(319.4 sq.m.),5,6,3+,"store room,pooja room,servant room,study room","Corner Villa, Sushant Lok Phase 3, Gurgaon, Ha...",4.0,North-East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...","Sushant lok-3\nBlock-B, corner villa at plot r...",[],"['Feng Shui / Vaastu Compliant', 'False Ceilin...","['Environment4 out of 5', 'Lifestyle4 out of 5...",E69994668
2,5 Bedroom House for sale in Dayanand Colony,house,independent,Dayanand Colony,1.25,11574.0,1080.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,5,5,1,pooja room,"34/4, 8 Biswa, Daya Kishan Katariya Marg, Daya...",2.0,South,0 to 1 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Interested to sell independent house/villa.It ...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5...",S68260580
3,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,Sector 79,0.95,6209.0,1530.0,Super Built up area 1530(142.14 sq.m.),2,2,3,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",7.0,North-East,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Right next to the new golf course road, m3m an...","['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5...",NaN
4,3 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,Sector 22,3.20,11500.0,2783.0,Super Built up area 2781(258.36 sq.m.),3,4,3+,not available,"204, Sector 22 Gurgaon, Gurgaon, Haryana",2.0,North-East,Within 6 months,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Right in heart of gurgaon and delhi is just 2k...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E...",NaN

In [1084]:
df['sector'] = df['sector'].str.lower()

In [1085]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss,sector 85,1.18,7170.0,1646.0,Super Built up area 1640(152.36 sq.m.)Built Up...,2,2,3,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Ekta Hospital', ...",This lovely 2 bhk apartment/flat in sector 85 ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5...",NaN
1,5 Bedroom House for sale in Sushant Lok Phase 3,house,independent,sushant lok phase 3,8.31,24171.0,3438.0,Plot area 382(319.4 sq.m.),5,6,3+,"store room,pooja room,servant room,study room","Corner Villa, Sushant Lok Phase 3, Gurgaon, Ha...",4.0,North-East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...","Sushant lok-3\nBlock-B, corner villa at plot r...",[],"['Feng Shui / Vaastu Compliant', 'False Ceilin...","['Environment4 out of 5', 'Lifestyle4 out of 5...",E69994668
2,5 Bedroom House for sale in Dayanand Colony,house,independent,dayanand colony,1.25,11574.0,1080.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,5,5,1,pooja room,"34/4, 8 Biswa, Daya Kishan Katariya Marg, Daya...",2.0,South,0 to 1 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Interested to sell independent house/villa.It ...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5...",S68260580
3,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,sector 79,0.95,6209.0,1530.0,Super Built up area 1530(142.14 sq.m.),2,2,3,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",7.0,North-East,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Right next to the new golf course road, m3m an...","['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5...",NaN
4,3 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,sector 22,3.20,11500.0,2783.0,Super Built up area 2781(258.36 sq.m.),3,4,3+,not available,"204, Sector 22 Gurgaon, Gurgaon, Haryana",2.0,North-East,Within 6 months,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Right in heart of gurgaon and delhi is just 2k...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E...",NaN

In [1086]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 81                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 70                                                     53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
laxman vihar                                                  27
sector 71                                                     27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
dlf phase 3                                                   22
sector 111                                                    22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 74                                                     18
sector 78                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sushant lok phase 3                                           16
sector 110                                                    16
sector 99                                                     16
sector 63                                                     15
sector 14                                                     15
sector 60                                                     15
rajendra park                                                 14
sector 3                                                      14
sector 52                                                     14
sector 76                                                     14
sector 1 imt manesar                                          14
gwal pahari                                                   14
dlf phase 5                                                   14
sector 53                                                     14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
sector 38                                                     12
uppals southend                                               12
sohna road                                                    12
sector 50                                                     12
sector 93                                                     12
sector 39                                                     12
sector 31                                                     12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 4                                                       9
south city 1                                                   9
sector 95a                                                     9
ashok vihar phase 2                                            9
sector 55                                                      9
sector 59                                                      8
sector 89 a                                                    8
palam vihar extension                                          8
mehrauli  road                                                 8
malibu town                                                    8
sector 57                                                      8
c block sushant lok phase 1                                    8
sector 40                                                      8
sector 10a                                                     8
sector 43                                                      8
sector 51                                                      7
sector 36 sohna                                                7
sector 26                                                      7
new colony                                                     7
sector 11                                                      7
surat nagar 1                                                  7
sector 58                                                      7
mianwali colony                                                7
dwarka expressway                                              7
jyoti park                                                     6
rajiv nagar                                                    6
ashok vihar                                                    6
jacobpura                                                      6
sector 5                                                       6
sector 1                                                       6
dayanand colony                                                5
chakkarpur                                                     5
sector 28                                                      5
sector 23a                                                     5
new palam vihar                                                5
ansal plaza                                                    5
sushant lok phase 2                                            5
sector 2                                                       5
sector 80                                                      5
greenwood city                                                 5
subhash nagar                                                  5
sector 9                                                       5
arjun nagar                                                    5
sector 30                                                      5
saraswati vihar                                                5
manesar                                                        5
sector 105                                                     5
new                                                            4
bhim nagar                                                     4
madanpuri                                                      4
valley view estate                                             4
shivaji nagar                                                  4
sector 45                                                      4
garhi harsaru                                                  4
ravi nagar                                                     4
imt manesar                                                    4
surya vihar                                                    4
baldev nagar                                                   4
sector 12a                                                     4
krishna colony                                                 4
sector 12                                                      4
sector 3a                                                      4
sector 17                                                      4
vishnu garden                                                  4
sector 6                                                       4
adarsh nagar                                                   4
bhondsi                                                        4
shivpuri                                                       4
devilal colony                                                 4
dharam colony                                                  4
sector 36                                                      4
suncity                                                        4
patel nagar                                                    3
laxmi garden                                                   3
sector 73                                                      3
prem nagar                                                     3
sector 23                                                      3
sector 15                                                      3
a block sushant lok phase 1                                    3
maruti kunj                                                    3
sector 17b                                                     3
gandhi nagar                                                   3
shakti nagar                                                   3
b block sushant lok phase 1                                    3
sector 17a                                                     3
sector 27                                                      3
sector 88b                                                     3
mg road                                                        3
sector 8                                                       3
sector 110 a                                                   3
sector 21                                                      2
nars                                                           2
hira nagar                                                     2
west rajiv nagar                                               2
sector 15 part 1                                               2
mayfield garden                                                2
block a surya vihar                                            2
surat nagar phase 2                                            2
daulatabad                                                     2
new basti                                                      2
sushant lok                                                    2
farukhnagar                                                    2
new palam vihar phase 2                                        2
rosewood                                                       2
golf course ext road                                           2
shankar vihar                                                  2
sector-11 sohna                                                2
rajiv chowk                                                    2
sector 41                                                      2
sispal vihar                                                   2
golf course road                                               2
sohna  road                                                    2
shanti nagar                                                   2
mohan nagar                                                    2
iffco chowk                                                    2
sector-2 sohna                                                 2
sector 32                                                      2
faridabad road                                                 2
samaspur                                                       2
sector 24                                                      2
pratap nagar                                                   2
, delhi ncr                                                    2
bissar                                                         2
bhawani enclave                                                2
lajpat nagar                                                   2
ambience island                                                2
acharya puri                                                   2
surat nagar                                                    2
manohar nagar                                                  2
sector 15 part 2                                               2
new palam vihar phase 1                                        2
sheetla colony                                                 2
sector 37a                                                     1
old delhi road, opp sector-14                                  1
sector 5 chowk                                                 1
huda saraswati vihar                                           1
tekchand nagar                                                 1
g block dlf city phase 1                                       1
sec 3 bhim vihar part 1 bhimgher kheri                         1
ram nagar                                                      1
bhimgarh kheri phase 3                                         1
mahavir pura                                                   1
saraswati enclave                                              1
urban estate, sector 5                                         1
devi lal colony gali no 12 gurgaon nr omkar public school      1
near khandsa road                                              1
sadar bazar                                                    1
ravi nager basai road                                          1
sector 17c                                                     1
nirvana country pocket h                                       1
sector 9b                                                      1
naharpur rupa                                                  1
udyog vihar phase 1                                            1
block h ashok vihar phase iii extension                        1
part 3 sector 5                                                1
dhankot                                                        1
khandsa                                                        1
block g sector-57                                              1
south city                                                     1
saroop garden rajendra park                                    1
laxmna vihar, phase 2                                          1
sector-35 sohna                                                1
damdma                                                         1
godrej aria , sector 79 ,                                      1
garauli kalan                                                  1
sultanpur                                                      1
near euro                                                      1
gopal nagar, garhi ghasita, sonipat                            1
bptp                                                           1
rattan garden                                                  1
kheri                                                          1
alipur                                                         1
shivji park colony                                             1
sector 4 urban estate                                          1
om nagar                                                       1
anand garden, sector-105                                       1
carterpuri village                                             1
near nand hospital                                             1
sai kunj                                                       1
jat colony,fazilpur/taj nagar road                             1
b1 block sector 57                                             1
kanahi                                                         1
lucknow                                                        1
jacobpura near sadar bazar                                     1
sector 13                                                      1
sector 42                                                      1
ashok vihar phase i                                            1
civil l                                                        1
heritage city                                                  1
hsiidc plot sector 1 imt manesar                               1
v block dlf phase 3                                            1
ansal's palam vihar                                            1
pataudi road                                                   1
vir nagar                                                      1
ats marigold                                                   1
laxman vihar, railway road,                                    1
rajiv colony                                                   1
sector 37b                                                     1
sector-7 hous                                                  1
park view                                                      1
bhora kalan                                                    1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
sector-5 sohna                                                 1
sector 21a faridabad                                           1
new colony, sector 7                                           1
sector-5 sheetla colony                                        1
near sector 1 market                                           1
near pataudi chowk                                             1
ashok vihar phase 3                                            1
cyber city                                                     1
new jyoti park                                                 1
mahalaxmi garden, rajendra place                               1
Name: count, dtype: int64

In [1087]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [1088]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 33                                                     74
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 43                                                     67
sector 86                                                     67
sector 95                                                     66
sector 50                                                     65
sector 89                                                     64
sector 2                                                      63
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
sector 84                                                     51
sector 26                                                     50
sector 4                                                      49
sector 67                                                     48
sector 49                                                     48
sector 28                                                     47
sector 66                                                     46
sector 103                                                    45
sector 25                                                     43
sector 113                                                    43
sector 82                                                     42
sector 61                                                     42
sector 7                                                      39
sector 106                                                    38
sector 12                                                     37
manesar                                                       33
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 112                                                    24
sector 57                                                     24
sector 3                                                      24
sector 24                                                     24
sector 105                                                    23
sector 14                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
sector 11                                                     21
sector 82a                                                    20
sector 22                                                     20
sector 110                                                    19
sector 47                                                     19
sector 74                                                     18
sector 63a                                                    18
gwal pahari                                                   18
sector 78                                                     18
sector 62                                                     17
sector 91                                                     17
sector 99                                                     16
sector 63                                                     15
sector 60                                                     15
sector 53                                                     14
sector 52                                                     14
sector 55                                                     14
sector 76                                                     14
sector 36a                                                    13
sector 23                                                     13
sector 9                                                      13
sector 6                                                      13
sector 46                                                     13
sector 93                                                     12
sector 39                                                     12
sector 38                                                     12
sohna road road                                               12
sector 31                                                     12
sector 41                                                     11
sector 3 phase 3 extension                                    11
sector 9a                                                     11
sector 36                                                     11
sector 13                                                     10
sector 45                                                      9
sector 3 phase 2                                               9
sector 40                                                      8
sector 17                                                      8
sector 8                                                       8
sector 59                                                      8
sector 10a                                                     8
sector 51                                                      7
dwarka expressway                                              7
sector 58                                                      7
sector 5                                                       6
sector 21                                                      6
sector 1                                                       6
sector 15                                                      6
sector 30                                                      5
sector 80                                                      5
new sector 2                                                   5
new                                                            4
sector 73                                                      3
sector 88b                                                     3
sector 27                                                      3
sector 17a                                                     3
sector 17b                                                     3
new sector 2 phase 1                                           2
sector 15 part 2                                               2
manohar nagar                                                  2
sector-2 sohna road                                            2
sector 32                                                      2
, delhi ncr                                                    2
faridabad road                                                 2
sushant lok                                                    2
nars                                                           2
farukhnagar                                                    2
golf course ext road                                           2
ambience island                                                2
new sector 2 phase 2                                           2
block a sector 21                                              2
bissar                                                         2
golf course road                                               2
shankar vihar                                                  2
sispal vihar                                                   2
sector-11 sohna road                                           2
hira nagar                                                     2
rosewood                                                       2
surat nagar phase 2                                            2
sheetla colony                                                 2
pratap nagar                                                   2
shanti nagar                                                   2
sohna road  road                                               2
mohan nagar                                                    2
samaspur                                                       2
lajpat nagar                                                   2
surat nagar                                                    2
daulatabad                                                     2
new basti                                                      2
west sector 13                                                 2
sector 15 part 1                                               2
mayfield garden                                                2
acharya puri                                                   2
bhawani enclave                                                2
rajiv chowk                                                    2
iffco chowk                                                    2
sector 9b                                                      1
sai kunj                                                       1
carterpuri village                                             1
naharpur rupa                                                  1
near nand hospital                                             1
sector 3 phase i                                               1
near euro                                                      1
sultanpur                                                      1
bptp                                                           1
sector 50 pocket h                                             1
rattan garden                                                  1
kheri                                                          1
anand garden, sector-105                                       1
gopal nagar, garhi ghasita, sonipat                            1
jat colony,fazilpur/taj nagar road                             1
sector 4 urban estate                                          1
sector 42                                                      1
heritage city                                                  1
civil l                                                        1
hsiidc plot manesar                                            1
b1 block sector 57                                             1
ansal's sector 2                                               1
v block sector 24                                              1
saroop garden sector 105                                       1
godrej aria , sector 79 ,                                      1
laxmna vihar, phase 2                                          1
shivji park colony                                             1
sector-35 sohna road                                           1
south city                                                     1
om nagar                                                       1
damdma                                                         1
alipur                                                         1
garauli kalan                                                  1
ats marigold                                                   1
vir nagar                                                      1
pataudi road                                                   1
lucknow                                                        1
tekchand nagar                                                 1
park view                                                      1
sector 37b                                                     1
bhimgarh kheri phase 3                                         1
g block dlf city phase 1                                       1
ram nagar                                                      1
sector-7 hous                                                  1
sector 4, railway road,                                        1
rajiv colony                                                   1
kanahi                                                         1
sector 12 near sadar bazar                                     1
saraswati enclave                                              1
old delhi road, opp sector-14                                  1
huda sector 28                                                 1
sector 5 chowk                                                 1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 17c                                                     1
ravi nager basai road                                          1
mahavir pura                                                   1
urban estate, sector 5                                         1
khandsa                                                        1
dhankot                                                        1
udyog vihar phase 1                                            1
block g sector-57                                              1
sector 37a                                                     1
near khandsa road                                              1
sadar bazar                                                    1
part 3 sector 5                                                1
block h sector 3 phase iii extension                           1
devi lal colony gali no 12 gurgaon nr omkar public school      1
bhora kalan                                                    1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
sector-5 sohna road                                            1
sector 21a faridabad                                           1
sector 7, sector 7                                             1
sector-5 sheetla colony                                        1
near sector 1 market                                           1
near pataudi chowk                                             1
sector 3 phase 3                                               1
cyber city                                                     1
new sector 7                                                   1
mahasector 11, rajendra place                                  1
Name: count, dtype: int64

In [1089]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
334,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,Not Available,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN,NaN
631,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,Not Available,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN,NaN
1636,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,Not Available,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN,NaN
2715,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,Not Available,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,NaN

In [1090]:
df.loc[631,'sector'] = 'sector 37'
df.loc[1636,'sector'] = 'sector 92'
df.loc[334,'sector'] = 'sector 90'
df.loc[2715,'sector'] = 'sector 76'

In [1091]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
262,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.000,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",K38173331
648,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.220,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,Not Available,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",NaN
1357,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.285,3166.0,900.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,Not Available,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ...",NaN
1560,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.340,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5...",T69907288
2589,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.600,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,Not Available,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",NaN

In [1092]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [1093]:
df.shape

(3959, 22)

In [1094]:
# Manually corrected sector mappings (verified)

df.loc[955,  'sector'] = 'sector 51'   # mayfield garden
df.loc[956,  'sector'] = 'sector 43'   # sushant lok
df.loc[957,  'sector'] = 'sector 24'   # ambience island
df.loc[958,  'sector'] = 'sector 54'   # golf course road
df.loc[959,  'sector'] = 'sector 67'   # golf course ext road
df.loc[960,  'sector'] = 'sector 102'  # dwarka expressway
df.loc[961,  'sector'] = 'sector 23'   # palam vihar
df.loc[962,  'sector'] = 'sector 29'   # iffco chowk
df.loc[963,  'sector'] = 'sector 14'   # rajiv chowk
df.loc[964,  'sector'] = 'sector 24'   # cyber city
df.loc[965,  'sector'] = 'sector 41'   # south city
df.loc[966,  'sector'] = 'sector 49'   # rosewood
df.loc[967,  'sector'] = 'sector 50'   # nirvana country

# Your additional corrections
df.loc[2800, 'sector'] = 'sector 92'
df.loc[2838, 'sector'] = 'sector 90'
df.loc[2857, 'sector'] = 'sector 76'

In [1095]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   112
sector 85                                                    110
sector 92                                                    106
sector 69                                                     94
sector 90                                                     92
sector 81                                                     89
sector 65                                                     89
sector 109                                                    86
sector 79                                                     80
sector 104                                                    73
sector 33                                                     73
sector 83                                                     69
sector 43                                                     68
sector 86                                                     67
sector 37d                                                    67
sector 50                                                     65
sector 95                                                     65
sector 89                                                     64
sector 2                                                      63
sector 107                                                    60
sector 108                                                    59
sector 56                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     52
sector 84                                                     51
sector 26                                                     50
sector 4                                                      49
sector 67                                                     49
sector 49                                                     49
sector 28                                                     47
sector 66                                                     45
sector 103                                                    45
sector 25                                                     43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     41
sector 7                                                      38
sector 106                                                    38
sector 12                                                     37
sector 54                                                     32
manesar                                                       32
sector 99a                                                    31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 24                                                     26
sector 110                                                    24
sector 57                                                     24
sector 3                                                      24
sector 14                                                     24
sector 112                                                    24
sector 105                                                    23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
sector 11                                                     21
sector 22                                                     20
sector 82a                                                    20
sector 47                                                     19
sector 63a                                                    18
sector 74                                                     18
gwal pahari                                                   18
sector 91                                                     17
sector 62                                                     17
sector 78                                                     17
sector 76                                                     16
sector 99                                                     16
sector 63                                                     15
sector 23                                                     14
sector 52                                                     14
sector 55                                                     14
sector 60                                                     14
sector 36a                                                    13
sector 53                                                     13
sector 9                                                      13
sector 6                                                      13
sector 46                                                     13
sector 41                                                     12
sector 39                                                     12
sector 38                                                     12
sohna road road                                               12
sector 93                                                     12
sector 31                                                     12
sector 3 phase 3 extension                                    11
sector 9a                                                     11
sector 36                                                     11
sector 13                                                     10
sector 45                                                      9
sector 3 phase 2                                               9
sector 40                                                      8
sector 59                                                      8
sector 8                                                       8
sector 51                                                      8
sector 17                                                      8
sector 10a                                                     8
sector 58                                                      7
dwarka expressway                                              7
sector 5                                                       6
sector 21                                                      6
sector 1                                                       6
sector 15                                                      6
sector 30                                                      5
sector 80                                                      5
new sector 2                                                   5
sector 73                                                      3
sector 17b                                                     3
sector 88b                                                     3
sector 27                                                      3
sector 17a                                                     3
hira nagar                                                     2
, delhi ncr                                                    2
sector 15 part 2                                               2
manohar nagar                                                  2
golf course road                                               2
new sector 2 phase 1                                           2
sector 32                                                      2
sector-2 sohna road                                            2
faridabad road                                                 2
sushant lok                                                    2
ambience island                                                2
golf course ext road                                           2
daulatabad                                                     2
nars                                                           2
shankar vihar                                                  2
surat nagar                                                    2
new basti                                                      2
block a sector 21                                              2
sispal vihar                                                   2
sector-11 sohna road                                           2
rosewood                                                       2
farukhnagar                                                    2
rajiv chowk                                                    2
sheetla colony                                                 2
pratap nagar                                                   2
shanti nagar                                                   2
sohna road  road                                               2
mohan nagar                                                    2
samaspur                                                       2
bissar                                                         2
lajpat nagar                                                   2
surat nagar phase 2                                            2
acharya puri                                                   2
west sector 13                                                 2
mayfield garden                                                2
sector 15 part 1                                               2
new sector 2 phase 2                                           2
bhawani enclave                                                2
iffco chowk                                                    2
sector 3 phase i                                               1
sector 50 pocket h                                             1
sector 9b                                                      1
carterpuri village                                             1
naharpur rupa                                                  1
near nand hospital                                             1
sai kunj                                                       1
near euro                                                      1
sultanpur                                                      1
bptp                                                           1
rattan garden                                                  1
kheri                                                          1
gopal nagar, garhi ghasita, sonipat                            1
anand garden, sector-105                                       1
jat colony,fazilpur/taj nagar road                             1
garauli kalan                                                  1
sector 4 urban estate                                          1
heritage city                                                  1
civil l                                                        1
v block sector 24                                              1
hsiidc plot manesar                                            1
b1 block sector 57                                             1
ansal's sector 2                                               1
saroop garden sector 105                                       1
south city                                                     1
godrej aria , sector 79 ,                                      1
sector 29                                                      1
sector-35 sohna road                                           1
shivji park colony                                             1
laxmna vihar, phase 2                                          1
om nagar                                                       1
damdma                                                         1
alipur                                                         1
sector 37                                                      1
sector-7 hous                                                  1
pataudi road                                                   1
ats marigold                                                   1
lucknow                                                        1
kanahi                                                         1
sector 37b                                                     1
park view                                                      1
g block dlf city phase 1                                       1
tekchand nagar                                                 1
bhimgarh kheri phase 3                                         1
vir nagar                                                      1
sector 4, railway road,                                        1
rajiv colony                                                   1
sector 42                                                      1
sector 12 near sadar bazar                                     1
old delhi road, opp sector-14                                  1
sector 5 chowk                                                 1
sec 3 bhim vihar part 1 bhimgher kheri                         1
huda sector 28                                                 1
ram nagar                                                      1
ravi nager basai road                                          1
sadar bazar                                                    1
saraswati enclave                                              1
urban estate, sector 5                                         1
dhankot                                                        1
sector 17c                                                     1
udyog vihar phase 1                                            1
block g sector-57                                              1
sector 37a                                                     1
near khandsa road                                              1
mahavir pura                                                   1
part 3 sector 5                                                1
block h sector 3 phase iii extension                           1
devi lal colony gali no 12 gurgaon nr omkar public school      1
bhora kalan                                                    1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
sector-5 sohna road                                            1
sector 21a faridabad                                           1
sector 7, sector 7                                             1
sector-5 sheetla colony                                        1
near sector 1 market                                           1
near pataudi chowk                                             1
sector 3 phase 3                                               1
cyber city                                                     1
new sector 7                                                   1
mahasector 11, rajendra place                                  1
Name: count, dtype: int64

In [1096]:
df['sector'] = df['sector'].str.replace(
    r'.*(sector[-\s]*\d+[a-z]?).*',
    r'\1',
    regex=True
)

In [1097]:
df['sector'] = (
    df['sector']
    .str.replace('-', ' ', regex=False)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [1098]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   112
sector 85                                                    110
sector 92                                                    106
sector 69                                                     94
sector 90                                                     92
sector 81                                                     89
sector 65                                                     89
sector 109                                                    86
sector 79                                                     81
sector 2                                                      75
sector 104                                                    73
sector 33                                                     73
sector 83                                                     69
sector 43                                                     68
sector 86                                                     67
sector 37d                                                    67
sector 50                                                     66
sector 95                                                     65
sector 89                                                     64
sector 107                                                    60
sector 108                                                    59
sector 48                                                     56
sector 56                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     52
sector 84                                                     51
sector 4                                                      51
sector 26                                                     50
sector 67                                                     49
sector 49                                                     49
sector 28                                                     48
sector 3                                                      47
sector 103                                                    45
sector 66                                                     45
sector 113                                                    43
sector 25                                                     43
sector 61                                                     42
sector 82                                                     41
sector 7                                                      41
sector 106                                                    38
sector 12                                                     38
manesar                                                       32
sector 54                                                     32
sector 99a                                                    31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 24                                                     27
sector 71                                                     27
sector 57                                                     26
sector 14                                                     25
sector 105                                                    25
sector 11                                                     24
sector 110                                                    24
sector 112                                                    24
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 47                                                     19
gwal pahari                                                   18
sector 74                                                     18
sector 63a                                                    18
sector 78                                                     17
sector 62                                                     17
sector 91                                                     17
sector 76                                                     16
sector 99                                                     16
sector 63                                                     15
sector 52                                                     14
sector 23                                                     14
sector 60                                                     14
sector 55                                                     14
sohna road road                                               14
sector 46                                                     13
sector 6                                                      13
sector 9                                                      13
sector 36a                                                    13
sector 53                                                     13
sector 93                                                     12
sector 41                                                     12
sector 13                                                     12
sector 31                                                     12
sector 38                                                     12
sector 39                                                     12
sector 36                                                     11
sector 5                                                      11
sector 9a                                                     11
sector 15                                                     10
sector 45                                                      9
sector 17                                                      8
sector 8                                                       8
sector 59                                                      8
sector 51                                                      8
sector 40                                                      8
sector 10a                                                     8
sector 21                                                      8
sector 58                                                      7
sector 1                                                       7
dwarka expressway                                              7
sector 30                                                      5
sector 80                                                      5
sector 27                                                      3
sector 73                                                      3
sector 88b                                                     3
sector 17b                                                     3
sector 17a                                                     3
acharya puri                                                   2
faridabad road                                                 2
mayfield garden                                                2
golf course road                                               2
manohar nagar                                                  2
golf course ext road                                           2
hira nagar                                                     2
new basti                                                      2
sushant lok                                                    2
bhawani enclave                                                2
nars                                                           2
farukhnagar                                                    2
rosewood                                                       2
rajiv chowk                                                    2
daulatabad                                                     2
ambience island                                                2
surat nagar phase 2                                            2
sispal vihar                                                   2
sheetla colony                                                 2
sector 32                                                      2
, delhi ncr                                                    2
pratap nagar                                                   2
mohan nagar                                                    2
shanti nagar                                                   2
samaspur                                                       2
bissar                                                         2
surat nagar                                                    2
lajpat nagar                                                   2
iffco chowk                                                    2
shankar vihar                                                  2
near euro                                                      1
sultanpur                                                      1
sai kunj                                                       1
naharpur rupa                                                  1
near nand hospital                                             1
sector 9b                                                      1
rattan garden                                                  1
shivji park colony                                             1
alipur                                                         1
damdma                                                         1
om nagar                                                       1
jat colony,fazilpur/taj nagar road                             1
garauli kalan                                                  1
sector 37                                                      1
gopal nagar, garhi ghasita, sonipat                            1
kheri                                                          1
bptp                                                           1
carterpuri village                                             1
hsiidc plot manesar                                            1
sector 35                                                      1
south city                                                     1
sector 29                                                      1
laxmna vihar, phase 2                                          1
ats marigold                                                   1
vir nagar                                                      1
rajiv colony                                                   1
pataudi road                                                   1
kanahi                                                         1
civil l                                                        1
sector 42                                                      1
lucknow                                                        1
heritage city                                                  1
g block dlf city phase 1                                       1
sec 3 bhim vihar part 1 bhimgher kheri                         1
ram nagar                                                      1
bhimgarh kheri phase 3                                         1
tekchand nagar                                                 1
park view                                                      1
sector 37b                                                     1
ravi nager basai road                                          1
sadar bazar                                                    1
mahavir pura                                                   1
saraswati enclave                                              1
udyog vihar phase 1                                            1
dhankot                                                        1
sector 37a                                                     1
sector 17c                                                     1
near khandsa road                                              1
devi lal colony gali no 12 gurgaon nr omkar public school      1
bhora kalan                                                    1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
sector 21a                                                     1
near pataudi chowk                                             1
cyber city                                                     1
Name: count, dtype: int64

In [1099]:
# Major known localities → sectors

df.loc[df['sector'] == 'mayfield garden', 'sector'] = 'sector 51'
df.loc[df['sector'] == 'sushant lok', 'sector'] = 'sector 43'
df.loc[df['sector'] == 'rosewood', 'sector'] = 'sector 49'
df.loc[df['sector'] == 'ambience island', 'sector'] = 'sector 24'
df.loc[df['sector'] == 'golf course road', 'sector'] = 'sector 54'
df.loc[df['sector'] == 'golf course ext road', 'sector'] = 'sector 67'
df.loc[df['sector'] == 'iffco chowk', 'sector'] = 'sector 29'
df.loc[df['sector'] == 'rajiv chowk', 'sector'] = 'sector 14'
df.loc[df['sector'] == 'cyber city', 'sector'] = 'sector 24'
df.loc[df['sector'] == 'south city', 'sector'] = 'sector 41'

# Roads / belts (mapped to dominant nearby sectors)

df.loc[df['sector'] == 'faridabad road', 'sector'] = 'sector 46'
df.loc[df['sector'] == 'sohna road', 'sector'] = 'sector 48'
df.loc[df['sector'] == 'pataudi road', 'sector'] = 'sector 10'
df.loc[df['sector'] == 'near pataudi chowk', 'sector'] = 'sector 10'
df.loc[df['sector'] == 'near khandsa road', 'sector'] = 'sector 37'

# Older / central colonies (commonly mapped)

df.loc[df['sector'] == 'acharya puri', 'sector'] = 'sector 7'
df.loc[df['sector'] == 'sheetla colony', 'sector'] = 'sector 5'
df.loc[df['sector'] == 'pratap nagar', 'sector'] = 'sector 6'
df.loc[df['sector'] == 'shanti nagar', 'sector'] = 'sector 11'
df.loc[df['sector'] == 'lajpat nagar', 'sector'] = 'sector 7'
df.loc[df['sector'] == 'mahavir pura', 'sector'] = 'sector 5'
df.loc[df['sector'] == 'saraswati enclave', 'sector'] = 'sector 9'

# Villages / outskirts (nearest administrative sector)

df.loc[df['sector'] == 'farukhnagar', 'sector'] = 'sector 15'
df.loc[df['sector'] == 'daulatabad', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'dhankot', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'samaspur', 'sector'] = 'sector 37'
df.loc[df['sector'] == 'bissar', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'alipur', 'sector'] = 'sector 110'
df.loc[df['sector'] == 'bhora kalan', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'begampur khatola', 'sector'] = 'sector 95'

# Industrial / employment areas

df.loc[df['sector'] == 'udyog vihar phase 1', 'sector'] = 'sector 20'
df.loc[df['sector'] == 'hsiidc plot manesar', 'sector'] = 'sector 1 manesar'

# Catch small spelling / mixed cases

df.loc[df['sector'] == ', delhi ncr', 'sector'] = 'sector 14'
df.loc[df['sector'] == 'manohar nagar', 'sector'] = 'sector 8'
df.loc[df['sector'] == 'hira nagar', 'sector'] = 'sector 10'
df.loc[df['sector'] == 'shankar vihar', 'sector'] = 'sector 23'
df.loc[df['sector'] == 'bhawani enclave', 'sector'] = 'sector 9'
df.loc[df['sector'] == 'sispal vihar', 'sector'] = 'sector 49'

In [1100]:
df['sector'].value_counts()

sector
sector 48                                                    219
sector 102                                                   115
sector 85                                                    110
sector 92                                                    106
sector 69                                                     94
sector 90                                                     92
sector 65                                                     89
sector 81                                                     89
sector 109                                                    86
sector 79                                                     81
sector 2                                                      75
sector 104                                                    73
sector 33                                                     73
sector 43                                                     70
sector 83                                                     69
sector 95                                                     69
sector 86                                                     67
sector 37d                                                    67
sector 50                                                     66
sector 89                                                     64
sector 107                                                    60
sector 108                                                    59
sector 56                                                     56
sector 70a                                                    54
sector 49                                                     53
sector 37c                                                    53
sector 70                                                     52
sector 4                                                      51
sector 67                                                     51
sector 84                                                     51
sector 26                                                     50
sector 28                                                     48
sector 3                                                      47
sector 66                                                     45
sector 103                                                    45
sector 7                                                      45
sector 25                                                     43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     41
sector 106                                                    38
sector 12                                                     38
sector 54                                                     34
manesar                                                       32
sector 99a                                                    31
sector 24                                                     30
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 14                                                     29
sector 71                                                     27
sector 57                                                     26
sector 11                                                     26
sector 105                                                    25
sector 110                                                    25
sector 112                                                    24
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 47                                                     19
sector 63a                                                    18
gwal pahari                                                   18
sector 74                                                     18
sector 91                                                     17
sector 78                                                     17
sector 62                                                     17
sector 23                                                     16
sector 9                                                      16
sector 99                                                     16
sector 76                                                     16
sector 6                                                      15
sector 63                                                     15
sector 46                                                     15
sohna road road                                               14
sector 60                                                     14
sector 5                                                      14
sector 52                                                     14
sector 55                                                     14
sector 36a                                                    13
sector 53                                                     13
sector 41                                                     13
sector 15                                                     12
sector 13                                                     12
sector 31                                                     12
sector 38                                                     12
sector 39                                                     12
sector 93                                                     12
sector 36                                                     11
sector 9a                                                     11
sector 51                                                     10
sector 8                                                      10
sector 45                                                      9
sector 59                                                      8
sector 10a                                                     8
sector 17                                                      8
sector 40                                                      8
sector 21                                                      8
sector 1                                                       7
sector 58                                                      7
dwarka expressway                                              7
sector 80                                                      5
sector 30                                                      5
sector 10                                                      4
sector 37                                                      4
sector 27                                                      3
sector 73                                                      3
sector 88b                                                     3
sector 17b                                                     3
sector 29                                                      3
sector 17a                                                     3
sector 32                                                      2
mohan nagar                                                    2
new basti                                                      2
nars                                                           2
surat nagar                                                    2
surat nagar phase 2                                            2
near euro                                                      1
sultanpur                                                      1
rattan garden                                                  1
sector 9b                                                      1
near nand hospital                                             1
naharpur rupa                                                  1
sai kunj                                                       1
carterpuri village                                             1
bptp                                                           1
kheri                                                          1
laxmna vihar, phase 2                                          1
damdma                                                         1
shivji park colony                                             1
sector 35                                                      1
garauli kalan                                                  1
om nagar                                                       1
gopal nagar, garhi ghasita, sonipat                            1
jat colony,fazilpur/taj nagar road                             1
sector 42                                                      1
heritage city                                                  1
lucknow                                                        1
kanahi                                                         1
vir nagar                                                      1
rajiv colony                                                   1
sector 1 manesar                                               1
civil l                                                        1
sector 37b                                                     1
ats marigold                                                   1
tekchand nagar                                                 1
park view                                                      1
bhimgarh kheri phase 3                                         1
ram nagar                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
g block dlf city phase 1                                       1
sadar bazar                                                    1
ravi nager basai road                                          1
sector 20                                                      1
sector 17c                                                     1
sector 37a                                                     1
devi lal colony gali no 12 gurgaon nr omkar public school      1
hno 13 sagar enclave sura                                      1
sector 21a                                                     1
Name: count, dtype: int64

In [1101]:
# Surat Nagar & nearby

df.loc[df['sector'] == 'surat nagar', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'surat nagar phase 2', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'new basti', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'nars', 'sector'] = 'sector 102'

# Mohan Nagar / Old Gurgaon side

df.loc[df['sector'] == 'mohan nagar', 'sector'] = 'sector 7'
df.loc[df['sector'] == 'shivji park colony', 'sector'] = 'sector 7'
df.loc[df['sector'] == 'ram nagar', 'sector'] = 'sector 7'
df.loc[df['sector'] == 'rajiv colony', 'sector'] = 'sector 7'

# Central / market areas

df.loc[df['sector'] == 'sadar bazar', 'sector'] = 'sector 14'
df.loc[df['sector'] == 'near nand hospital', 'sector'] = 'sector 14'
df.loc[df['sector'] == 'near euro', 'sector'] = 'sector 14'

# Palam / surrounding villages

df.loc[df['sector'] == 'naharpur rupa', 'sector'] = 'sector 27'
df.loc[df['sector'] == 'kanahi', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'carterpuri village', 'sector'] = 'sector 23'
df.loc[df['sector'] == 'sai kunj', 'sector'] = 'sector 23'
df.loc[df['sector'] == 'laxmna vihar, phase 2', 'sector'] = 'sector 23'

# Industrial / builder areas

df.loc[df['sector'] == 'bptp', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'ats marigold', 'sector'] = 'sector 76'
df.loc[df['sector'] == 'park view', 'sector'] = 'sector 37'
df.loc[df['sector'] == 'tekchand nagar', 'sector'] = 'sector 9'

# Villages / outskirts

df.loc[df['sector'] == 'kheri', 'sector'] = 'sector 37'
df.loc[df['sector'] == 'garauli kalan', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'bhimgarh kheri phase 3', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'devi lal colony gali no 12 gurgaon nr omkar public school', 'sector'] = 'sector 95'

# Roads / belts

df.loc[df['sector'] == 'ravi nager basai road', 'sector'] = 'sector 37'
df.loc[df['sector'] == 'jat colony,fazilpur/taj nagar road', 'sector'] = 'sector 37'

# DLF / premium zones

df.loc[df['sector'] == 'g block dlf city phase 1', 'sector'] = 'sector 26'
df.loc[df['sector'] == 'heritage city', 'sector'] = 'sector 25'

# Manesar side

df.loc[df['sector'] == 'sector 1 manesar', 'sector'] = 'sector 1 manesar'
# Localities mapped to nearest commonly used sectors

df.loc[df['sector'] == 'damdma', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'om nagar', 'sector'] = 'sector 7'
df.loc[df['sector'] == 'vir nagar', 'sector'] = 'sector 9'
df.loc[df['sector'] == 'civil l', 'sector'] = 'sector 14'
df.loc[df['sector'] == 'hno 13 sagar enclave sura', 'sector'] = 'sector 95'

# Villages / outskirts (mapped conservatively)

df.loc[df['sector'] == 'sec 3 bhim vihar part 1 bhimgher kheri', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'gopal nagar, garhi ghasita, sonipat', 'sector'] = 'sonipat (outside gurgaon)'

# Non-Gurgaon / out-of-scope locations (keep explicit)

df.loc[df['sector'] == 'lucknow', 'sector'] = 'lucknow (outside gurgaon)'
# Sultanpur & nearby
df.loc[df['sector'] == 'sultanpur', 'sector'] = 'sector 47'
# Old Gurgaon / central colonies
df.loc[df['sector'] == 'rattan garden', 'sector'] = 'sector 15'
df.loc[df['sector'] == 'om nagar', 'sector'] = 'sector 7'
df.loc[df['sector'] == 'vir nagar', 'sector'] = 'sector 9'
df.loc[df['sector'] == 'civil l', 'sector'] = 'sector 14'

# Villages / outskirts (conservative mapping)
df.loc[df['sector'] == 'damdma', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'sec 3 bhim vihar part 1 bhimgher kheri', 'sector'] = 'sector 95'
df.loc[df['sector'] == 'hno 13 sagar enclave sura', 'sector'] = 'sector 95'

# Outside Gurgaon (do NOT force into sectors)
df.loc[df['sector'] == 'gopal nagar, garhi ghasita, sonipat', 'sector'] = 'sonipat (outside gurgaon)'
df.loc[df['sector'] == 'lucknow', 'sector'] = 'lucknow (outside gurgaon)'

# Major corridors / localities

df.loc[df['sector'] == 'dwarka expressway', 'sector'] = 'sector 102'
df.loc[df['sector'] == 'sohna road road', 'sector'] = 'sector 48'
df.loc[df['sector'] == 'gwal pahari', 'sector'] = 'sector 58'
df.loc[df['sector'] == 'sector 1 manesar', 'sector'] = 'manesar'

In [1102]:
df.loc[
    df['address'].str.contains('New Palam Vihar', case=False, na=False),
    ['property_name', 'address', 'sector']
].index

Index([132, 262, 648, 1280, 1357, 1560, 2028, 2098, 2589], dtype='int64')

In [1103]:
df.loc[[132, 262, 648, 1280, 1357, 1560, 2028, 2098, 2589],'sector'] = 'sector 110'

In [1104]:
df = df[~df['sector'].isin([
    'sonipat (outside gurgaon)',
    'lucknow (outside gurgaon)'
])]

In [1105]:
df['sector'].value_counts()

sector
sector 48     233
sector 102    132
sector 85     110
sector 92     106
sector 69      94
sector 90      92
sector 81      89
sector 65      89
sector 109     86
sector 79      81
sector 95      75
sector 104     73
sector 33      73
sector 43      70
sector 83      69
sector 86      67
sector 37d     67
sector 50      66
sector 2       66
sector 89      64
sector 107     60
sector 108     59
sector 56      56
sector 70a     54
sector 49      53
sector 37c     53
sector 70      52
sector 84      51
sector 26      51
sector 4       51
sector 7       51
sector 67      51
sector 28      48
sector 3       47
sector 66      45
sector 103     45
sector 25      44
sector 113     43
sector 61      42
sector 82      41
sector 106     38
sector 12      38
sector 54      34
sector 110     34
manesar        33
sector 14      33
sector 99a     31
sector 24      30
sector 68      30
sector 77      29
sector 72      29
sector 71      27
sector 57      26
sector 11      26
sector 105     25
sector 58      25
sector 112     24
sector 88a     23
sector 111     22
sector 67a     22
sector 82a     20
sector 47      20
sector 22      20
sector 23      19
sector 74      18
sector 63a     18
sector 9       18
sector 62      17
sector 91      17
sector 78      17
sector 76      17
sector 99      16
sector 6       15
sector 63      15
sector 46      15
sector 55      14
sector 5       14
sector 60      14
sector 52      14
sector 53      13
sector 41      13
sector 15      13
sector 36a     13
sector 31      12
sector 93      12
sector 38      12
sector 39      12
sector 13      12
sector 9a      11
sector 36      11
sector 51      10
sector 8       10
sector 45       9
sector 10a      8
sector 40       8
sector 37       8
sector 21       8
sector 59       8
sector 17       8
sector 1        7
sector 80       5
sector 30       5
sector 10       4
sector 27       4
sector 73       3
sector 88b      3
sector 17b      3
sector 17a      3
sector 29       3
sector 32       2
sector 9b       1
sector 35       1
sector 42       1
sector 37b      1
sector 17c      1
sector 20       1
sector 37a      1
sector 21a      1
Name: count, dtype: int64

In [1106]:
df.shape

(3957, 22)

In [1107]:
df.duplicated().sum()

np.int64(0)

In [1108]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Sector 85 Gurgaon,flat,ss,sector 85,1.18,7170.0,1646.0,Super Built up area 1640(152.36 sq.m.)Built Up...,2,2,3,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Ekta Hospital', ...",This lovely 2 bhk apartment/flat in sector 85 ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5...",NaN
1,5 Bedroom House for sale in Sushant Lok Phase 3,house,independent,sector 57,8.31,24171.0,3438.0,Plot area 382(319.4 sq.m.),5,6,3+,"store room,pooja room,servant room,study room","Corner Villa, Sushant Lok Phase 3, Gurgaon, Ha...",4.0,North-East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...","Sushant lok-3\nBlock-B, corner villa at plot r...",[],"['Feng Shui / Vaastu Compliant', 'False Ceilin...","['Environment4 out of 5', 'Lifestyle4 out of 5...",E69994668
2,5 Bedroom House for sale in Dayanand Colony,house,independent,sector 6,1.25,11574.0,1080.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,5,5,1,pooja room,"34/4, 8 Biswa, Daya Kishan Katariya Marg, Daya...",2.0,South,0 to 1 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Interested to sell independent house/villa.It ...,"['1 Wardrobe', '1 Modular Kitchen', 'No AC', '...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5...",S68260580
3,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,sector 79,0.95,6209.0,1530.0,Super Built up area 1530(142.14 sq.m.),2,2,3,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",7.0,North-East,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Right next to the new golf course road, m3m an...","['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5...",NaN
4,3 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,sector 22,3.20,11500.0,2783.0,Super Built up area 2781(258.36 sq.m.),3,4,3+,not available,"204, Sector 22 Gurgaon, Gurgaon, Haryana",2.0,North-East,Within 6 months,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Right in heart of gurgaon and delhi is just 2k...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E...",NaN

In [1109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3957 entries, 0 to 3958
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3957 non-null   object
 1   property_type    3957 non-null   object
 2   society          3957 non-null   object
 3   sector           3957 non-null   object
 4   price            3937 non-null   float64
 5   price_per_sqft   3937 non-null   float64
 6   Estimated_area   3937 non-null   float64
 7   areaWithType     3957 non-null   object
 8   bedRoom          3957 non-null   int64
 9   bathroom         3957 non-null   int64
 10  balcony          3957 non-null   object
 11  additionalRoom   3957 non-null   object
 12  address          3946 non-null   object
 13  floorNum         3938 non-null   float64
 14  facing           3957 non-null   object
 15  agePossession    3956 non-null   object
 16  nearbyLocations  3752 non-null   object
 17  description      3957 non-null   object
 18  furnishDetails   2925 non-null   object
 19  features         3251 non-null   object
 20  rating           3510 non-null   object
 21  property_id      962 non-null    object
dtypes: float64(4), int64(2), object(16)
memory usage: 711.0+ KB

In [1110]:
df.drop(columns=['rating','property_id','property_name','address'], inplace=True)

In [1111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3957 entries, 0 to 3958
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_type    3957 non-null   object
 1   society          3957 non-null   object
 2   sector           3957 non-null   object
 3   price            3937 non-null   float64
 4   price_per_sqft   3937 non-null   float64
 5   Estimated_area   3937 non-null   float64
 6   areaWithType     3957 non-null   object
 7   bedRoom          3957 non-null   int64
 8   bathroom         3957 non-null   int64
 9   balcony          3957 non-null   object
 10  additionalRoom   3957 non-null   object
 11  floorNum         3938 non-null   float64
 12  facing           3957 non-null   object
 13  agePossession    3956 non-null   object
 14  nearbyLocations  3752 non-null   object
 15  description      3957 non-null   object
 16  furnishDetails   2925 non-null   object
 17  features         3251 non-null   object
dtypes: float64(4), int64(2), object(12)
memory usage: 587.4+ KB

In [1112]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [1113]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,Estimated_area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
1836,flat,sanskriti apartment,sector 10a,1.10,6666.0,1650.0,Carpet area: 1650 (153.29 sq.m.),3,3,3,not available,2.0,Not Available,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Kamla Hospital Gurgaon...",This 3 bhk apartment is available for sale in ...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Lift(s)', 'Water Storage', 'Park', 'Visitor ..."
1081,flat,shapoorji pallonji joyville gurugram,sector 102,1.05,11475.0,915.0,Carpet area: 915 (85.01 sq.m.),2,2,2,not available,0.0,Not Available,Mar 2024,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",New upcoming available in next 6-9 months,[],"['Feng Shui / Vaastu Compliant', 'Security / F..."
3886,flat,m3m heights,sector 65,3.00,18000.0,1667.0,Super Built up area 1828(169.83 sq.m.),3,3,3,not available,20.0,South-East,By 2024,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...",Bang on golf course extension and next to bigg...,"['1 Modular Kitchen', '1 Chimney', 'No AC', 'N...","['Power Back-up', 'Security / Fire Alarm', 'In..."
2225,flat,dlf the ultima,sector 81,2.25,10553.0,2132.0,Super Built up area 2132(198.07 sq.m.),3,3,3+,servant room,6.0,East,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",Urgent available for sale 3 bhk flat in sector...,"['1 Fridge', '5 Fan', '1 Exhaust Fan', '5 Geys...","['Centrally Air Conditioned', 'Water purifier'..."
1429,flat,the close north,sector 50,2.70,9980.0,2705.0,Super Built up area 2605(242.01 sq.m.),3,3,3+,servant room,3.0,South,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",This 3 bhk apartment is available for sale in ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [1114]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)